version: "3"
   
services:
  db:
    build:
      context: ./docker/postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  web:
    build:
      context: .
    volumes:
      - ./:/user/src/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - web
      - db
    ports:
      - "80:80" 
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs:/etc/nginx/conf.d:ro
      - ./static/:/config/static

volumes:
  dbdata: