CREATE SCHEMA IF NOT EXISTS content;

CREATE USER admin WITH PASSWORD 'ololo11';

-- CREATE DATABASE movies;
GRANT ALL PRIVILEGES ON DATABASE movies TO admin;
GRANT ALL PRIVILEGES ON SCHEMA content TO admin;


